import {afterEach,describe,expect,it,vi} from 'vitest';
import {io,type Socket} from 'socket.io-client';
import {createApplication} from '../apps/server/src/app';
import {Roboflow,landmarks,workflow} from '../apps/server/src/roboflow';

const config={apiKey:'test-private-key',origin:'https://rally.example',model:'yolov8n-pose-640',maxStreams:2,region:'us'};
const predictions={image:{width:640,height:360},predictions:[{confidence:.9,keypoints:Array.from({length:17},(_,class_id)=>({class_id,x:320,y:180,confidence:.9}))}]};
function provider(){const request=vi.fn<typeof fetch>(async url=>new Response(JSON.stringify(String(url).includes('turn_config')?{iceServers:[{urls:['turn:relay.example:3478'],username:'temporary',credential:'temporary'}]}:String(url).includes('terminate')?{ok:true}:{sdp:'v=0\r\n',type:'answer',context:{pipeline_id:'pipeline-id'}}),{status:200}));return{vision:new Roboflow(config,request),request};}
const cleanups:Array<()=>Promise<unknown>>=[];
afterEach(async()=>{for(const clean of cleanups.splice(0).reverse())await clean();});
async function server(production=false){const {vision,request}=provider(),app=createApplication({origin:config.origin,vision,production});await new Promise<void>(r=>app.http.listen(0,'127.0.0.1',r));cleanups.push(()=>app.close());const address=app.http.address() as {port:number},base=`http://127.0.0.1:${address.port}`;
 const post=async(path:string,body:unknown,token='')=>fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(body)});
 async function client(){const {token}=await (await post('/api/session',{})).json();const socket=io(base,{auth:{token},transports:['websocket'],reconnection:false});cleanups.push(async()=>{socket.disconnect();});await new Promise<void>((resolve,reject)=>{socket.once('connect',resolve);socket.once('connect_error',reject);});return{socket,token};}
 return{...app,request,post,client,base};}
function emit(socket:Socket,event:string,data:unknown){return socket.timeout(2000).emitWithAck(event,data);}

describe('Roboflow managed stream contract',()=>{
 it('accepts SDP answers when managed workers omit the optional pipeline id',async()=>{
  const request=vi.fn<typeof fetch>(async url=>new Response(JSON.stringify(String(url).includes('turn_config')?{iceServers:[{urls:['turn:relay.example:3478']}]}:{type:'answer',sdp:'v=0\r\n',context:{pipeline_id:null}})));
  const vision=new Roboflow(config,request),lease=vision.reserve('owner');
  expect(await vision.start(lease,{type:'offer',sdp:'v=0\r\n'})).toEqual({type:'answer',sdp:'v=0\r\n'});
  await vision.stop(lease.id);expect(vision.authenticate(lease.secret)).toBeUndefined();
 });
 it('uses a fixed authenticated webhook and does not return provider secrets',async()=>{const {vision,request}=provider(),lease=vision.reserve('owner');const answer=await vision.start(lease,{type:'offer',sdp:'v=0\r\n'});const payload=JSON.parse(request.mock.calls[1][1]!.body as string);expect(payload.api_key).toBe(config.apiKey);expect(payload.workflow_configuration.workflow_specification).toEqual(workflow(config,lease));expect(payload.webrtc_realtime_processing).toBe(true);expect(payload.processing_timeout).toBe(900);expect(JSON.stringify(answer)).not.toContain(lease.secret);expect(JSON.stringify(answer)).not.toContain(config.apiKey);await vision.stop(lease.id);expect(vision.authenticate(lease.secret)).toBeUndefined();expect(String(request.mock.calls.at(-1)![0])).toContain('/terminate');});
 it('requires TURN and enforces per-player and global capacity',async()=>{const {vision}=provider();vision.reserve('a');expect(()=>vision.reserve('a')).toThrow('already');vision.reserve('b');expect(()=>vision.reserve('c')).toThrow('busy');const noRelay=new Roboflow(config,async()=>new Response(JSON.stringify([{urls:['stun:example.org']}])));await expect(noRelay.iceServers()).rejects.toThrow('relay');});
 it('terminates a worker that finishes starting after cancellation',async()=>{let release!:(response:Response)=>void;const request=vi.fn<typeof fetch>(async url=>String(url).includes('turn_config')?new Response(JSON.stringify([{urls:['turn:example.org']}])):String(url).includes('terminate')?new Response('{}'):new Promise(r=>{release=r;}));const vision=new Roboflow(config,request),lease=vision.reserve('a');const pending=vision.start(lease,{type:'offer',sdp:'v=0'});await vi.waitFor(()=>expect(release).toBeTypeOf('function'));await vision.stop(lease.id);release(new Response(JSON.stringify({type:'answer',sdp:'v=0',context:{pipeline_id:'late'}})));await expect(pending).rejects.toThrow('cancelled');expect(String(request.mock.calls.at(-1)![0])).toContain('/late/terminate');});
 it('normalizes COCO joints and rejects ambiguous multiple people',()=>{const p=landmarks(predictions);expect(p[11]).toEqual({x:.5,y:.5,visibility:.9});expect(p[15].visibility).toBe(.9);expect(landmarks({...predictions,predictions:[...predictions.predictions,...predictions.predictions]})).toEqual([]);expect(landmarks({image:{width:null,height:null},predictions:[]})).toEqual([]);expect(()=>landmarks({image:{width:0,height:360},predictions:predictions.predictions})).toThrow();});
});
describe('cloud HTTP and socket boundary',()=>{
 it('accepts production same-origin polling without Origin and rejects other sites',async()=>{
  const s=await server(true),url=s.base+'/socket.io/?EIO=4&transport=polling';
  const same=await fetch(url,{headers:{'Sec-Fetch-Site':'same-origin'}});
  expect(same.status).toBe(200);expect(await same.text()).toContain('"sid"');
  expect((await fetch(url,{headers:{'Sec-Fetch-Site':'cross-site'}})).status).toBe(403);
  expect((await fetch(url,{headers:{Origin:'https://untrusted.example','Sec-Fetch-Site':'same-origin'}})).status).toBe(403);
  expect((await fetch(url)).status).toBe(403);
 });
 it('rejects unissued browser credentials and foreign origins',async()=>{const s=await server();const bad=io(s.base,{auth:{token:'made-up'},transports:['websocket'],reconnection:false});cleanups.push(async()=>{bad.disconnect();});const error=await new Promise<Error>(r=>bad.once('connect_error',r));expect(error.message).toContain('Session');const r=await fetch(s.base+'/api/session',{method:'POST',headers:{Origin:'https://untrusted.example','Content-Type':'application/json'},body:'{}'});expect(r.status).toBe(403);expect((await s.post('/api/vision/prepare',{},'fake')).status).toBe(401);});
 it('keeps rooms isolated and ignores client form submissions',async()=>{const s=await server(),a=await s.client(),b=await s.client();const ra=await emit(a.socket,'create',{}),rb=await emit(b.socket,'create',{});expect(ra.code).not.toBe(rb.code);a.socket.emit('form_result',{hitId:'1',score:100000});a.socket.emit('input',{sequence:1,keys:['KeyD'],ready:true,x:999});await vi.waitFor(()=>expect(s.rooms.rooms.get(ra.code)!.players[0]!.input.x).toBeGreaterThan(-.2));expect(s.rooms.rooms.get(rb.code)!.players[0]!.input.x).toBe(-.2);expect(s.rooms.rooms.get(ra.code)!.game.score).toBe(0);});
 it('authenticates fresh callbacks and revokes them when switching to keyboard',async()=>{const s=await server(),a=await s.client();const room=await emit(a.socket,'create',{});const setup=await (await s.post('/api/vision/prepare',{},a.token)).json(),lease=s.vision.leases.get(setup.id)!;const data={frame:1,timestamp:new Date().toISOString(),predictions};expect((await s.post('/api/vision/results',data,'fake')).status).toBe(401);expect((await s.post('/api/vision/results',data,lease.secret)).status).toBe(204);expect(s.rooms.rooms.get(room.code)!.players[0]!.result).not.toBeNull();expect((await s.post('/api/vision/results',data,lease.secret)).status).toBe(202);expect((await s.post('/api/vision/results',{...data,frame:2,timestamp:new Date(Date.now()-1000).toISOString()},lease.secret)).status).toBe(202);await a.socket.timeout(2000).emitWithAck('keyboard');expect((await s.post('/api/vision/results',{...data,frame:3},lease.secret)).status).toBe(401);});
 it('binds a stream to its player and rejects arbitrary workflow and callback choices',async()=>{const s=await server(),a=await s.client(),b=await s.client();await emit(a.socket,'create',{});await emit(b.socket,'create',{});const setup=await(await s.post('/api/vision/prepare',{},a.token)).json();expect((await s.post('/api/vision/start',{id:setup.id,offer:{type:'offer',sdp:'v=0'}},b.token)).status).toBe(409);const response=await s.post('/api/vision/start',{id:setup.id,offer:{type:'offer',sdp:'v=0'},workflowSpec:{evil:true},callback:'https://evil.example'},a.token);expect(response.status).toBe(200);const init=s.request.mock.calls.find(c=>String(c[0]).includes('initialise'))!;expect(String(init[1]!.body)).not.toContain('evil');});
});
