import {describe,it,expect} from 'vitest';
import {Rooms} from '../apps/server/src/rooms';
const packet={keys:[],ready:true,sequence:1};
describe('cloud rooms',()=>{
 it('isolates concurrent rooms and rejects a third player',()=>{const rooms=new Rooms(),a=rooms.create('a','a'),b=rooms.create('b','b');expect(a.code).not.toBe(b.code);rooms.join(a.code,'c','c');expect(()=>rooms.join(a.code,'d','d')).toThrow('full');a.game.score=123;expect(b.game.score).toBe(0);});
 it('recovers the same seat without accepting duplicate ownership',()=>{const rooms=new Rooms(),r=rooms.create('a','old');expect(()=>rooms.join(r.code,'a','other')).toThrow();rooms.disconnect(r,0);expect(rooms.join(r.code,'a','new').side).toBe(0);expect(r.players[0]?.socketId).toBe('new');});
 it('accepts key intent, ignores forged coordinates and rejects stale sequences',()=>{const rooms=new Rooms(),r=rooms.create('a','a');rooms.input(r,0,{...packet,x:900,score:100000,keys:['KeyD']});rooms.tick(r,.1);expect(r.players[0]!.input.x).toBeCloseTo(.14);rooms.input(r,0,{...packet,keys:['KeyA']});expect(r.players[0]!.keys.has('KeyD')).toBe(true);rooms.input(r,0,{...packet,sequence:2,keys:['Invalid']});expect(r.players[0]?.sequence).toBe(1);});
 it('pauses when a player disconnects or camera data becomes stale',()=>{const rooms=new Rooms(),r=rooms.create('a','a');rooms.join(r.code,'b','b');rooms.input(r,0,packet);rooms.input(r,1,packet);rooms.tick(r,3.1);expect(r.phase).toBe('playing');const elapsed=r.game.elapsed;rooms.setCamera(r,0,true);rooms.tick(r,.05);expect(r.phase).toBe('paused');expect(r.game.elapsed).toBe(elapsed);rooms.disconnect(r,1);expect(r.players[1]?.ready).toBe(false);});
 it('runs practice simulation on the server',()=>{const rooms=new Rooms(),r=rooms.create('a','a','practice');rooms.input(r,0,packet);rooms.tick(r,3.1);rooms.tick(r,.1);expect(r.phase).toBe('playing');expect(r.game.elapsed).toBeGreaterThan(0);});
 it('runs both keyboard rackets on the server',()=>{const rooms=new Rooms(),r=rooms.create('a','a','duo');rooms.input(r,0,{...packet,keys:['KeyD','ArrowRight']});rooms.tick(r,.1);expect(r.players[0]!.input.x).toBeGreaterThan(-.2);expect(r.players[1]!.input.x).toBeLessThan(.2);});
 it('clears old scoring jobs and votes on replay',()=>{const rooms=new Rooms(),r=rooms.create('a','a','practice');r.phase='results';const game=r.game;rooms.replay(r,0);expect(r.game).not.toBe(game);expect(r.grades).toEqual([]);expect(r.phase).toBe('lobby');});
 it('releases seats on explicit leave and expires abandoned rooms',()=>{const rooms=new Rooms(),r=rooms.create('a','a');rooms.leave(r,0);expect(rooms.rooms.size).toBe(0);const second=rooms.create('b','b');rooms.disconnect(second,0);rooms.expire(Date.now()+61000);expect(rooms.rooms.size).toBe(0);});
 it('never serializes session tokens or form history',()=>{const rooms=new Rooms(),r=rooms.create('secret','a');const s=JSON.stringify(rooms.snapshot(r));expect(s).not.toContain('secret');expect(s).not.toContain('pendingGrades');expect(s).not.toContain('pose');});
});
